apiVersion: batch/v1
kind: CronJob
metadata:
  name: esvtr-renew-tokens
  namespace: external-secrets
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: esvtr-renew-tokens-container
            image: curlimages/curl 
            command: ["/bin/sh", "/scripts/script.sh"]
            securityContext:
              runAsUser: 0
            env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: esvtr-master-token
                  key: token
            envFrom:
            - configMapRef:
                name: esvtr-config
            volumeMounts:
            - name: esvtr-accessor-list
              mountPath: /tmp/accessor.lst
              subPath: accessor.lst
            - name: script-volume
              mountPath: /scripts/script.sh
              subPath: script.sh
          restartPolicy: Never
          volumes:
          - name: esvtr-accessor-list
            configMap:
              name: esvtr-accessor-list
          - name: script-volume
            configMap:
              name: esvtr-script